const express = require('express');
const router = express.Router();
const cleanBody = require('../middlewares/cleanbody');
const AuthController = require('../src/users/user.controller');
router.post('/signup', cleanBody, AuthController.Signup);
router.post('/login', cleanBody, AuthController.Login);
router.post('/activate', cleanBody, AuthController.Activate);
router.patch('/forgot', cleanBody, AuthController.ForgotPassword);
router.patch('/reset', cleanBody, AuthController.ResetPassword);
router.patch('/resend', cleanBody, AuthController.ResendCode);
router.patch('/send', cleanBody, AuthController.SendCallId);
router.get('/getAllUsers, cleanBody, AuthController.GetUsers);
router.get('/getAllDoctors, cleanBody, AuthController.GetDoctors);
module.exports = router;
